// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: rpc.proto

package jwtx

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Jwtx_MakeToken_FullMethodName   = "/jwtx.jwtx/MakeToken"
	Jwtx_CheckToken_FullMethodName  = "/jwtx.jwtx/CheckToken"
	Jwtx_DeleteToken_FullMethodName = "/jwtx.jwtx/DeleteToken"
)

// JwtxClient is the client API for Jwtx service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JwtxClient interface {
	// 生成 token（登录）
	MakeToken(ctx context.Context, in *MakeToken_Request, opts ...grpc.CallOption) (*MakeToken_Response, error)
	// 校验 token（拓展校验、刷新 token）
	CheckToken(ctx context.Context, in *CheckToken_Request, opts ...grpc.CallOption) (*CheckToken_Response, error)
	// 移除 token（安全退出）
	DeleteToken(ctx context.Context, in *DeleteToken_Request, opts ...grpc.CallOption) (*DeleteToken_Response, error)
}

type jwtxClient struct {
	cc grpc.ClientConnInterface
}

func NewJwtxClient(cc grpc.ClientConnInterface) JwtxClient {
	return &jwtxClient{cc}
}

func (c *jwtxClient) MakeToken(ctx context.Context, in *MakeToken_Request, opts ...grpc.CallOption) (*MakeToken_Response, error) {
	out := new(MakeToken_Response)
	err := c.cc.Invoke(ctx, Jwtx_MakeToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jwtxClient) CheckToken(ctx context.Context, in *CheckToken_Request, opts ...grpc.CallOption) (*CheckToken_Response, error) {
	out := new(CheckToken_Response)
	err := c.cc.Invoke(ctx, Jwtx_CheckToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jwtxClient) DeleteToken(ctx context.Context, in *DeleteToken_Request, opts ...grpc.CallOption) (*DeleteToken_Response, error) {
	out := new(DeleteToken_Response)
	err := c.cc.Invoke(ctx, Jwtx_DeleteToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JwtxServer is the server API for Jwtx service.
// All implementations must embed UnimplementedJwtxServer
// for forward compatibility
type JwtxServer interface {
	// 生成 token（登录）
	MakeToken(context.Context, *MakeToken_Request) (*MakeToken_Response, error)
	// 校验 token（拓展校验、刷新 token）
	CheckToken(context.Context, *CheckToken_Request) (*CheckToken_Response, error)
	// 移除 token（安全退出）
	DeleteToken(context.Context, *DeleteToken_Request) (*DeleteToken_Response, error)
	mustEmbedUnimplementedJwtxServer()
}

// UnimplementedJwtxServer must be embedded to have forward compatible implementations.
type UnimplementedJwtxServer struct {
}

func (UnimplementedJwtxServer) MakeToken(context.Context, *MakeToken_Request) (*MakeToken_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeToken not implemented")
}
func (UnimplementedJwtxServer) CheckToken(context.Context, *CheckToken_Request) (*CheckToken_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckToken not implemented")
}
func (UnimplementedJwtxServer) DeleteToken(context.Context, *DeleteToken_Request) (*DeleteToken_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteToken not implemented")
}
func (UnimplementedJwtxServer) mustEmbedUnimplementedJwtxServer() {}

// UnsafeJwtxServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JwtxServer will
// result in compilation errors.
type UnsafeJwtxServer interface {
	mustEmbedUnimplementedJwtxServer()
}

func RegisterJwtxServer(s grpc.ServiceRegistrar, srv JwtxServer) {
	s.RegisterService(&Jwtx_ServiceDesc, srv)
}

func _Jwtx_MakeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeToken_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JwtxServer).MakeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Jwtx_MakeToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JwtxServer).MakeToken(ctx, req.(*MakeToken_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Jwtx_CheckToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckToken_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JwtxServer).CheckToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Jwtx_CheckToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JwtxServer).CheckToken(ctx, req.(*CheckToken_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Jwtx_DeleteToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteToken_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JwtxServer).DeleteToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Jwtx_DeleteToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JwtxServer).DeleteToken(ctx, req.(*DeleteToken_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Jwtx_ServiceDesc is the grpc.ServiceDesc for Jwtx service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Jwtx_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jwtx.jwtx",
	HandlerType: (*JwtxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MakeToken",
			Handler:    _Jwtx_MakeToken_Handler,
		},
		{
			MethodName: "CheckToken",
			Handler:    _Jwtx_CheckToken_Handler,
		},
		{
			MethodName: "DeleteToken",
			Handler:    _Jwtx_DeleteToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
