// Code generated by goctl. DO NOT EDIT.
// Source: rpc.proto

package server

import (
	"context"

	"main/base/service/jwtx"
	"main/base/service/jwtx/private/rpc/internal/logic"
	"main/base/service/jwtx/private/rpc/internal/svc"
)

type JwtxServer struct {
	svcCtx *svc.ServiceContext
	jwtx.UnimplementedJwtxServer
}

func NewJwtxServer(svcCtx *svc.ServiceContext) *JwtxServer {
	return &JwtxServer{
		svcCtx: svcCtx,
	}
}

// 生成 token
func (s *JwtxServer) MakeToken(ctx context.Context, in *jwtx.MakeToken_Request) (*jwtx.MakeToken_Response, error) {
	l := logic.NewMakeTokenLogic(ctx, s.svcCtx)
	return l.MakeToken(in)
}

// 校验 token
func (s *JwtxServer) CheckToken(ctx context.Context, in *jwtx.CheckToken_Request) (*jwtx.CheckToken_Response, error) {
	l := logic.NewCheckTokenLogic(ctx, s.svcCtx)
	return l.CheckToken(in)
}
